#!/usr/bin/env python3
"""Provisioner daemon — host-side process that materializes per-user engine
containers in response to file-based flag drops from the API.

The API container (which has zero host privileges) signals provisioning
by writing into ``~/swarm/ionic/data/users/_queue/<id>.provision`` or
``<id>.teardown``. This daemon polls the queue every POLL_INTERVAL seconds
and acts on those flags:

  *.provision  → generate ~/swarm/ionic/users.yml.d/<id>.yml with the
                 per-user compose fragment, then `docker compose up -d
                 ionic-engine-<id>` from the swarm root.
  *.teardown   → docker compose stop + rm the container, remove the
                 fragment file, soft-move data/users/<id>/ to
                 data/users/_deleted/<id>_<timestamp>/ for the 30-day
                 retention window.

All actions are journaled to data/users/_queue/audit.log as JSON Lines.

Runs as a systemd service on the host (NOT a container). The unit file
lives at /etc/systemd/system/foundation-provisioner.service — see the
README in this repo for the contents. The daemon must run as a user
that's in the `docker` group so `docker compose` works without sudo.

Usage:
    python3 provisioner_daemon.py            # run forever, poll every 5s
    python3 provisioner_daemon.py --once     # one pass + exit (CI / testing)
    python3 provisioner_daemon.py --dry-run  # parse + log; don't shell out

Environment overrides:
    SWARM_ROOT            (default ~/swarm)
    IONIC_ROOT         (default $SWARM_ROOT/ionic)
    PROVISIONER_POLL_SEC  (default 5)
    PROVISIONER_AUDIT_LOG (default $IONIC_ROOT/data/users/_queue/audit.log)
"""
from __future__ import annotations

import argparse
import datetime
import json
import logging
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional


# ─── Configuration ─────────────────────────────────────────────────────────

SWARM_ROOT     = Path(os.environ.get("SWARM_ROOT",    os.path.expanduser("~/swarm")))
IONIC_ROOT  = Path(os.environ.get("IONIC_ROOT", str(SWARM_ROOT / "ionic")))

QUEUE_DIR        = IONIC_ROOT / "data" / "users" / "_queue"
USERS_FRAGMENTS  = IONIC_ROOT / "users.yml.d"
USER_DATA_DIR    = IONIC_ROOT / "data" / "users"
DELETED_DIR      = USER_DATA_DIR / "_deleted"
AUDIT_LOG_PATH   = Path(os.environ.get("PROVISIONER_AUDIT_LOG", str(QUEUE_DIR / "audit.log")))

POLL_INTERVAL    = float(os.environ.get("PROVISIONER_POLL_SEC", "5"))

# Image tag the per-user containers point at. Built from this repo's
# Dockerfile target=engine; one shared image for all users.
ENGINE_IMAGE_TAG = os.environ.get("IONIC_ENGINE_IMAGE", "ionic-engine:latest")

# Network the per-user engines join. Matches the existing per-bot network
# defined in ~/swarm/ionic/repo/docker-compose.yml.
ENGINE_NETWORK   = os.environ.get("IONIC_ENGINE_NETWORK", "ionic-net")

# Env file mounted into per-user engines via `env_file:` in the generated
# compose fragment. CRITICAL: this must NOT be the operator's `.env`
# (~/swarm/ionic/.env) — that file holds the operator's Oanda keys,
# Telegram bot token, JWT signing secret, etc. Per-user engines should
# see only the SHARED secrets (BROKER_KEY_MASTER for decrypting their own
# broker_keys row + shared 3rd-party API keys like BRAVE).
#
# Defaults to ~/swarm/ionic/users.env. The operator creates this
# file with the safe shared subset of secrets (see SAAS_PROVISIONER_PLAN.md
# §"Env isolation" or the comment in users.env.example).
SHARED_ENV_FILE  = Path(os.environ.get(
    "SHARED_ENV_FILE",
    str(IONIC_ROOT / "users.env"),
))

# Shared cross-bot identity DB (global.db). Mounted at /app/foundation
# inside per-user engines so they can decrypt their broker_keys row
# without bind-mounting any bot-specific dir.
FOUNDATION_DATA_DIR = Path(os.environ.get(
    "FOUNDATION_DATA_DIR",
    str(SWARM_ROOT / "foundation" / "data"),
))

logger = logging.getLogger(__name__)


# ─── Compose fragment template ─────────────────────────────────────────────


FRAGMENT_TEMPLATE = """\
# Auto-generated by provisioner_daemon.py at {ts}
# Source flag: data/users/_queue/{user_id}.provision
# DO NOT edit by hand — regenerate by removing this file + dropping a fresh
# .provision flag in _queue/.

services:
  ionic-engine-{user_id}:
    image: {image}
    container_name: ionic-engine-{user_id}
    restart: unless-stopped
    init: true
    environment:
      USER_ID:           "{user_id}"
      AGENT_NAME:        ionic
      SQLITE_PATH:       /app/data/users/{user_id}/ionic.db
      GLOBAL_DB_PATH:    /app/foundation/global.db
      CONFIG_PATH:       /app/data/users/{user_id}/Config.yaml
      HEARTBEAT_PATH:    /app/data/users/{user_id}/.engine_heartbeat
      RESTART_FLAG_PATH: /app/data/users/{user_id}/.restart_engine
    env_file:
      - {env_file}
    volumes:
      - {ionic_root}/data:/app/data:rw
      # Shared cross-bot identity DB (foundation/data/global.db)
      - {foundation_data}:/app/foundation:rw
    networks:
      - {network}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      # 10-min staleness window matches the operator's Dockerfile baseline
      # (-mmin -10). Tighter values (e.g. -mmin -2) cause healthcheck flapping
      # because the engine only touches the heartbeat at cycle START and a
      # user's `update_interval_min` can legitimately be 5-15 minutes.
      test:
        - CMD-SHELL
        - 'find /app/data/users/{user_id}/.engine_heartbeat -mmin -10 | grep -q . || exit 1'
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 90s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
"""


def render_fragment(user_id: int) -> str:
    """Build the per-user compose fragment text. Pure string substitution;
    no Docker calls; safe to call from tests."""
    return FRAGMENT_TEMPLATE.format(
        user_id         = user_id,
        ts              = datetime.datetime.now(datetime.timezone.utc).isoformat(),
        image           = ENGINE_IMAGE_TAG,
        env_file        = SHARED_ENV_FILE,
        ionic_root = IONIC_ROOT,
        foundation_data = FOUNDATION_DATA_DIR,
        network         = ENGINE_NETWORK,
    )


# ─── Audit log ─────────────────────────────────────────────────────────────


def audit(action: str, user_id: int, ok: bool, *, detail: str = "") -> None:
    """Append a JSON Lines record to the audit log. Best-effort — if the
    write fails (disk full, no permission), log a warning and proceed."""
    record = {
        "ts":      datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "action":  action,
        "user_id": user_id,
        "ok":      ok,
        "detail":  detail[:500],
    }
    try:
        AUDIT_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with AUDIT_LOG_PATH.open("a") as f:
            f.write(json.dumps(record) + "\n")
    except OSError as e:
        logger.warning(f"Failed to write audit record: {e}")


# ─── Concatenated users compose file ───────────────────────────────────────


# The combined file that the swarm-root docker-compose.yml `include:`s. This
# is the fallback strategy from SAAS_PROVISIONER_PLAN.md — Compose v2.20+
# is supposed to support globs in include, but in practice v5.x still treats
# `*.yml` as a literal filename. So we maintain a single concatenated file
# alongside the per-user fragments (which are kept for individual inspection
# and rollback). swarm-root compose includes the concatenated file by name.
USERS_COMBINED = IONIC_ROOT / "users.compose.yml"


def _regenerate_combined_compose() -> None:
    """Concatenate all users.yml.d/*.yml fragments into USERS_COMBINED.

    Reads every *.yml under USERS_FRAGMENTS, emits a single compose file
    with one `services:` block containing every per-user engine service.
    The file is rewritten from scratch on every provision/teardown, so
    deletions clean up naturally.

    Empty state: when no per-user engines exist, emits a no-op compose
    file with an empty services map (compose tolerates this).
    """
    USERS_FRAGMENTS.mkdir(parents=True, exist_ok=True)
    fragments = sorted(USERS_FRAGMENTS.glob("*.yml"))

    # Each fragment is itself a valid compose file with `services:` at top
    # level. We can't naively concat them (would produce two top-level
    # `services:` keys). Strip the leading `services:` from each fragment
    # and emit one combined block.
    lines = [
        "# Auto-generated by provisioner_daemon.py — DO NOT edit by hand.",
        f"# Last regeneration: {datetime.datetime.now(datetime.timezone.utc).isoformat()}",
        f"# Sources: {', '.join(f.name for f in fragments) if fragments else '(no per-user engines)'}",
        "",
    ]

    if not fragments:
        # Empty state: emit a syntactically-valid compose stub. Compose
        # tolerates an empty top-level `services: {}` without complaining.
        lines.append("services: {}")
    else:
        lines.append("services:")
        for frag in fragments:
            text = frag.read_text().rstrip()
            in_services = False
            for line in text.splitlines():
                if line.strip() == "services:":
                    in_services = True
                    continue
                if in_services:
                    lines.append(line)
            lines.append("")  # blank line between users

    USERS_COMBINED.write_text("\n".join(lines) + "\n")
    logger.info(f"Regenerated {USERS_COMBINED} ({len(fragments)} fragment(s))")


# ─── Subprocess wrapper (mockable in tests) ────────────────────────────────


def _run_compose(*args: str, dry_run: bool = False, timeout: int = 120) -> subprocess.CompletedProcess:
    """Wrapper around `docker compose <args>` rooted at SWARM_ROOT.

    Returns the CompletedProcess so callers can inspect returncode + stderr.
    In dry-run mode, returns a synthetic success without shelling out — useful
    for the daemon-self-test path and CI.
    """
    cmd = ["docker", "compose", *args]
    if dry_run:
        logger.info(f"[dry-run] would run: {' '.join(cmd)} (cwd={SWARM_ROOT})")
        return subprocess.CompletedProcess(cmd, 0, "", "")
    logger.info(f"Running: {' '.join(cmd)} (cwd={SWARM_ROOT})")
    return subprocess.run(
        cmd, cwd=SWARM_ROOT, capture_output=True, text=True, timeout=timeout,
    )


# ─── Provision ─────────────────────────────────────────────────────────────


def provision(user_id: int, *, dry_run: bool = False) -> bool:
    """Generate the compose fragment and bring up the user's engine container.

    Idempotent: regenerating an existing fragment + re-running `up -d` is
    safe (compose just confirms the container is in desired state).
    """
    USERS_FRAGMENTS.mkdir(parents=True, exist_ok=True)
    fragment_path = USERS_FRAGMENTS / f"{user_id}.yml"
    fragment_text = render_fragment(user_id)

    if dry_run:
        logger.info(f"[dry-run] would write fragment {fragment_path} ({len(fragment_text)} bytes)")
    else:
        fragment_path.write_text(fragment_text)
        logger.info(f"Wrote compose fragment {fragment_path}")
        # Regenerate the combined file the swarm-root compose include reads
        _regenerate_combined_compose()

    container = f"ionic-engine-{user_id}"
    result = _run_compose("up", "-d", container, dry_run=dry_run)
    ok = result.returncode == 0

    if ok:
        audit("provision", user_id, True, detail=f"container={container}")
    else:
        detail = (result.stderr or result.stdout or "")[:500]
        audit("provision", user_id, False, detail=detail)
        logger.error(f"provision({user_id}) failed: {detail}")

    return ok


# ─── Teardown ──────────────────────────────────────────────────────────────


def teardown(user_id: int, *, dry_run: bool = False) -> bool:
    """Stop + remove the user's container, remove the fragment, soft-move
    their data dir to _deleted/<id>_<ts>/.

    All four steps are best-effort and individually idempotent. We return
    True if the AUDIT-WORTHY work (container removal + dir move) completed,
    False if something hard-failed.
    """
    container = f"ionic-engine-{user_id}"
    fragment_path = USERS_FRAGMENTS / f"{user_id}.yml"
    user_dir = USER_DATA_DIR / str(user_id)

    # 1. Stop the container (no-op if already stopped/missing)
    _run_compose("stop", container, dry_run=dry_run, timeout=60)
    # 2. Remove the container (--force suppresses confirmation prompt)
    _run_compose("rm", "-f", container, dry_run=dry_run, timeout=60)

    # 3. Remove the fragment so future `up -d`s don't bring the container back
    if fragment_path.exists():
        if dry_run:
            logger.info(f"[dry-run] would unlink {fragment_path}")
        else:
            fragment_path.unlink()
            logger.info(f"Removed compose fragment {fragment_path}")
    # Regenerate the combined file the swarm-root compose include reads
    if not dry_run:
        _regenerate_combined_compose()

    # 4. Soft-move user data → _deleted/<id>_<utc-timestamp>/ for retention
    detail = "no_user_dir"
    if user_dir.exists():
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        dest = DELETED_DIR / f"{user_id}_{timestamp}"
        if dry_run:
            logger.info(f"[dry-run] would move {user_dir} → {dest}")
            detail = f"would_move_to={dest}"
        else:
            DELETED_DIR.mkdir(parents=True, exist_ok=True)
            shutil.move(str(user_dir), str(dest))
            detail = f"moved_to={dest}"
            logger.info(f"Soft-moved user dir → {dest}")

    audit("teardown", user_id, True, detail=detail)
    return True


# ─── Queue scan ────────────────────────────────────────────────────────────


def process_queue(*, dry_run: bool = False) -> int:
    """Scan QUEUE_DIR for *.provision and *.teardown files; process each;
    delete the flag once handled (whether the underlying op succeeded or
    not — failures stay in the audit log, not the queue).

    Returns the number of flags processed in this pass.
    """
    QUEUE_DIR.mkdir(parents=True, exist_ok=True)
    USERS_FRAGMENTS.mkdir(parents=True, exist_ok=True)
    DELETED_DIR.mkdir(parents=True, exist_ok=True)

    processed = 0
    # Sort so multiple flags drain in a stable order; provision before
    # teardown of the same id is intentional (would be a weird edge case
    # but the ordering is consistent — provision .p comes before .t).
    for flag in sorted(QUEUE_DIR.iterdir()):
        if flag.name == "audit.log":
            continue
        if flag.suffix not in (".provision", ".teardown"):
            continue
        try:
            user_id = int(flag.stem)
        except ValueError:
            logger.warning(f"Skipping malformed flag {flag.name}: stem is not an int")
            audit("skip", -1, False, detail=f"bad_flag={flag.name}")
            try:
                flag.unlink()
            except OSError:
                pass
            processed += 1   # malformed-but-consumed still counts
            continue

        try:
            if flag.suffix == ".provision":
                provision(user_id, dry_run=dry_run)
            else:
                teardown(user_id, dry_run=dry_run)
        except Exception as e:
            # Anything that escapes provision() / teardown() is audit-worthy
            # and shouldn't block the daemon. Capture, audit, move on.
            logger.exception(f"Exception handling {flag.name}: {e}")
            audit(flag.suffix.lstrip("."), user_id, False, detail=repr(e))
        finally:
            try:
                flag.unlink()
            except FileNotFoundError:
                pass
            except OSError as e:
                logger.warning(f"Failed to delete flag {flag.name}: {e}")
            processed += 1

    return processed


# ─── Daemon entry point ────────────────────────────────────────────────────


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Foundation per-user engine provisioner")
    parser.add_argument("--once", action="store_true",
                        help="Run a single queue pass and exit (CI / testing)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Log what WOULD happen but skip docker + file moves")
    parser.add_argument("--log-level", default="INFO",
                        choices=("DEBUG", "INFO", "WARNING", "ERROR"))
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s [provisioner] %(message)s",
    )

    logger.info(
        f"Provisioner starting: queue={QUEUE_DIR} fragments={USERS_FRAGMENTS} "
        f"poll={POLL_INTERVAL}s once={args.once} dry_run={args.dry_run}"
    )

    if args.once:
        n = process_queue(dry_run=args.dry_run)
        logger.info(f"Single-pass complete: processed {n} flag(s)")
        return 0

    # Long-running loop. systemd handles restart-on-failure.
    while True:
        try:
            n = process_queue(dry_run=args.dry_run)
            if n:
                logger.info(f"Processed {n} flag(s)")
        except Exception:
            logger.exception("process_queue() failed; sleeping then retrying")
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    sys.exit(main())
